### ISSUE TITLE
[Bug]: snapshot check not working

### ISSUE THREAD

**Issue by amette** [NETWAYS/check_elasticsearch#57]
### Please try to fill out as much of the information below as you can. Thank you!

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### Which version contains the bug?

0.5.0

### Describe the bug

Calling the snapshot subcommand fails with the error message: "[UNKNOWN] - could not decode snapshot response: json: cannot unmarshal object into Go struct field Snapshot.snapshots.failures of type string (*fmt.wrapError)"

### How to recreate the bug?

Call the snapshot subcommand against an elasticsearch cluster to which all other subcommands work perfectly.

**Comment by RincewindsHat** [comment]
Hi @amette,
Thank you for reporting this.
Could you tell us, which version of Elasticsearch you got there? Maybe the interface changed and the plugin doesn't know how to handle the other version.

**Comment by amette** [comment]
This is elasticsearch 8.13.4

**Comment by martialblog** [comment]
The snapshot subcommand is latest addition to the plugin, might be that there are still some kinks to work out. I don't think there were major API changes recently.

**Comment by martialblog** [comment]
I think I'm able to recreate this.

```
curl -k -X GET -u "elastic:REDACTED" "https://localhost:9200/_snapshot/my_repository/my_snapshot?pretty"
{
  "snapshots" : [
    {
      "snapshot" : "my_snapshot",
      "uuid" : "sCc_g6KISnmENHjH9YguHg",
      "repository" : "my_repository",
      "version_id" : 8505000,
      "version" : "8.14.0-8.14.1",
      "indices" : [
        ".security-7"
      ],
      "data_streams" : [ ],
      "include_global_state" : true,
      "state" : "SUCCESS",
      "start_time" : "2024-09-27T13:58:01.099Z",
      "start_time_in_millis" : 1727445481099,
      "end_time" : "2024-09-27T13:58:01.099Z",
      "end_time_in_millis" : 1727445481099,
      "duration_in_millis" : 0,
      "failures" : [ ],
      "shards" : {
        "total" : 1,
        "failed" : 0,
        "successful" : 1
      },
      "feature_states" : [
        {
          "feature_name" : "security",
          "indices" : [
            ".security-7"
          ]
        }
      ]
    }
  ],
  "total" : 1,
  "remaining" : 0
}
```

```
go run main.go --insecure --tls -U elastic -P REDACTED snapshot -r my_repository -s my_snapshot
[UNKNOWN] - could not decode snapshot response: json: cannot unmarshal object into Go struct field Snapshot.snapshots.feature_states of type string (*fmt.wrapError)
```

Different field to unmarshal but still

**Comment by martialblog** [comment]
Found the issue. feature_states and failures is not a []string.

I tried to find some examples of what failures actually look like but did not find any. For now I simply removed the used fields.

**Comment by martialblog** [comment]
@amette Hi, can you verify that this works now? https://github.com/NETWAYS/check_elasticsearch/releases/tag/v0.5.1-rc.1

**Comment by amette** [comment]
Hi  @martialblog, yes, now it works. Many thanks for the quick fix! :)
